name: smart_farmer_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  carousel_slider: ^5.0.0
  collection: ^1.18.0
  contentsize_tabbarview: ^0.0.2
  cupertino_icons: ^1.0.8
  delightful_toast: ^1.1.0
  easy_image_viewer: ^1.5.1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  geocoding: ^3.0.0
  get_it: ^7.7.0
  go_router: ^14.2.7
  http: ^1.2.2
  image: ^4.2.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  location: ^7.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  sidebarx: ^0.17.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
